import unittest

import context  # noqa: F401
import render

PROFILES = {
    "balanced": {
        "description": "test",
        "filters": [
            {"name": "hp", "label": "bq_highpass", "control": {"Freq": 300, "Q": 0.707}},
            {"name": "pr", "label": "bq_peaking",
             "control": {"Freq": 3000, "Q": 1.0, "Gain": 6.0}},
        ],
    },
}
TARGET = "alsa_output.pci-0000_00_1f.3.analog-stereo"


class TestRender(unittest.TestCase):
    def setUp(self):
        self.out = render.render(PROFILES, TARGET)

    def test_one_sink_per_profile(self):
        self.assertIn('node.name      = "eq_balanced"', self.out)
        self.assertIn("media.class    = Audio/Sink", self.out)

    def test_playback_is_pinned_to_the_hardware_sink(self):
        # Without target.object + dont-reconnect, WirePlumber re-routes each
        # chain to the current default sink, chaining the EQs into each other.
        self.assertIn('target.object       = "%s"' % TARGET, self.out)
        self.assertIn("node.dont-reconnect = true", self.out)

    def test_both_channels_are_built(self):
        for ch in ("l", "r"):
            self.assertIn("name = hp_%s" % ch, self.out)
            self.assertIn("name = pr_%s" % ch, self.out)

    def test_stages_are_linked_in_order_within_each_channel(self):
        for ch in ("l", "r"):
            self.assertIn('{ output = "hp_%s:Out" input = "pr_%s:In" }' % (ch, ch),
                          self.out)

    def test_controls_are_emitted(self):
        self.assertIn("Freq = 300", self.out)
        self.assertIn("Gain = 6.0", self.out)

    def test_single_stage_chain_still_renders_valid_links_block(self):
        one = {"solo": {"description": "d", "filters": [PROFILES["balanced"]["filters"][0]]}}
        out = render.render(one, TARGET)
        self.assertIn("# single-stage chain", out)
        self.assertEqual(out.count("context.modules = ["), 1)

    def test_config_is_marked_generated(self):
        self.assertTrue(self.out.startswith("# Generated by omarchy-eq"))

    def test_braces_balance(self):
        self.assertEqual(self.out.count("{"), self.out.count("}"))
        self.assertEqual(self.out.count("["), self.out.count("]"))


if __name__ == "__main__":
    unittest.main()
