import unittest

import context  # noqa: F401
import render

PROFILES = {
    "balanced": {
        "description": "test",
        "filters": [
            {"name": "hp", "label": "bq_highpass", "control": {"Freq": 300, "Q": 0.707}},
            {"name": "pr", "label": "bq_peaking",
             "control": {"Freq": 3000, "Q": 1.0, "Gain": 6.0}},
        ],
    },
}
TARGET = "alsa_output.pci-0000_00_1f.3.analog-stereo"


class TestRender(unittest.TestCase):
    def setUp(self):
        self.out = render.render([{"tag": "builtin", "target": TARGET,
                                   "label": "Built-in", "profiles": PROFILES}])

    def test_one_sink_per_profile(self):
        self.assertIn('node.name      = "eq_builtin_balanced"', self.out)
        self.assertIn("media.class    = Audio/Sink", self.out)

    def test_playback_is_pinned_to_the_hardware_sink(self):
        # Without target.object + dont-reconnect, WirePlumber re-routes each
        # chain to the current default sink, chaining the EQs into each other.
        self.assertIn('target.object       = "%s"' % TARGET, self.out)
        self.assertIn("node.dont-reconnect = true", self.out)

    def test_both_channels_are_built(self):
        for ch in ("l", "r"):
            self.assertIn("name = hp_%s" % ch, self.out)
            self.assertIn("name = pr_%s" % ch, self.out)

    def test_stages_are_linked_in_order_within_each_channel(self):
        for ch in ("l", "r"):
            self.assertIn('{ output = "hp_%s:Out" input = "pr_%s:In" }' % (ch, ch),
                          self.out)

    def test_controls_are_emitted(self):
        self.assertIn("Freq = 300", self.out)
        self.assertIn("Gain = 6.0", self.out)

    def test_single_stage_chain_still_renders_valid_links_block(self):
        one = {"solo": {"description": "d", "filters": [PROFILES["balanced"]["filters"][0]]}}
        out = render.render([{"tag": "builtin", "target": TARGET,
                              "label": "Built-in", "profiles": one}])
        self.assertIn("# single-stage chain", out)
        self.assertEqual(out.count("context.modules = ["), 1)

    def test_config_is_marked_generated(self):
        self.assertTrue(self.out.startswith("# Generated by omarchy-eq"))

    def test_braces_balance(self):
        self.assertEqual(self.out.count("{"), self.out.count("}"))
        self.assertEqual(self.out.count("["), self.out.count("]"))


if __name__ == "__main__":
    unittest.main()


class TestMultiDevice(unittest.TestCase):
    def setUp(self):
        self.out = render.render([
            {"tag": "builtin", "target": "alsa_output.pci-x",
             "label": "Built-in", "profiles": PROFILES},
            {"tag": "bt8ae6", "target": "bluez_output.AA.1",
             "label": "Nothing Ear", "profiles": PROFILES},
        ])

    def test_each_device_gets_its_own_sink_names(self):
        self.assertIn('node.name      = "eq_builtin_balanced"', self.out)
        self.assertIn('node.name      = "eq_bt8ae6_balanced"', self.out)

    def test_each_device_is_pinned_to_its_own_hardware_sink(self):
        self.assertIn('target.object       = "alsa_output.pci-x"', self.out)
        self.assertIn('target.object       = "bluez_output.AA.1"', self.out)

    def test_sink_names_are_unique_across_devices(self):
        import re
        names = re.findall(r'node\.name      = "([^"]+)"', self.out)
        self.assertEqual(len(names), len(set(names)))

    def test_descriptions_name_the_device(self):
        self.assertIn('"Built-in: Balanced"', self.out)
        self.assertIn('"Nothing Ear: Balanced"', self.out)

    def test_still_one_module_list(self):
        self.assertEqual(self.out.count("context.modules = ["), 1)
        self.assertEqual(self.out.count("{"), self.out.count("}"))

    def test_sink_name_helper_matches_what_is_rendered(self):
        self.assertEqual(render.sink_name("builtin", "balanced"), "eq_builtin_balanced")


IR = "/home/u/.local/state/omarchy-eq/Sennheiser HD 650 minimum phase 48000Hz.wav"
CONVOLUTION = {
    "room": {
        "description": "convolution",
        "ir_taps": 4096,
        "filters": [{"name": "conv", "label": "convolver",
                     "config_l": {"filename": IR, "channel": 0},
                     "config_r": {"filename": IR, "channel": 1}}],
    },
}


def device(profiles):
    return [{"tag": "builtin", "target": TARGET, "label": "Built-in",
             "profiles": profiles}]


def node_line(out, name):
    return [l for l in out.splitlines() if "name = %s " % name in l][0]


class TestStandaloneVsFragment(unittest.TestCase):
    """The standalone form is run as `pipewire -c`, a short-lived client of the
    real daemon, so reloading it after a headphone connect leaves every stream
    playing. The fragment costs a full daemon restart and is kept only for
    systems without systemd."""

    def setUp(self):
        self.standalone = render.render(device(PROFILES))
        self.fragment = render.render(device(PROFILES), standalone=False)

    def test_standalone_carries_the_preamble_a_bare_context_needs(self):
        # `pipewire -c` starts with nothing: it has to be told where the spa
        # factories live and which modules to load before a chain can exist.
        for want in ("context.properties", "context.spa-libs",
                     "audio.convert.* = audioconvert/libspa-audioconvert",
                     "libpipewire-module-protocol-native",
                     "libpipewire-module-client-node",
                     "libpipewire-module-adapter"):
            self.assertIn(want, self.standalone)

    def test_standalone_says_how_it_is_loaded(self):
        self.assertIn("pipewire -c", self.standalone)

    def test_the_fragment_carries_none_of_it(self):
        # A drop-in is merged into the daemon's own context, which already has
        # all of that; repeating it would load the modules twice.
        for unwanted in ("context.properties", "context.spa-libs",
                         "libpipewire-module-protocol-native",
                         "libpipewire-module-adapter", "pipewire -c"):
            self.assertNotIn(unwanted, self.fragment)

    def test_both_forms_are_marked_generated_and_open_one_module_list(self):
        for out in (self.standalone, self.fragment):
            self.assertTrue(out.startswith("# Generated by omarchy-eq"))
            self.assertEqual(out.count("context.modules = ["), 1)

    def test_both_forms_render_the_same_chains(self):
        self.assertIn('node.name      = "eq_builtin_balanced"', self.fragment)
        self.assertIn("name = hp_l", self.fragment)

    def test_both_forms_balance_their_brackets(self):
        for out in (self.standalone, self.fragment):
            self.assertEqual(out.count("{"), out.count("}"))
            self.assertEqual(out.count("["), out.count("]"))


class TestConvolution(unittest.TestCase):
    """A convolver takes its impulse response at instantiation time, which is a
    different kind of parameter from the runtime knobs -- hence `config`
    alongside `control`."""

    def setUp(self):
        self.out = render.render(device(CONVOLUTION))

    def test_the_impulse_response_is_passed_as_config_not_control(self):
        self.assertIn("config = {", self.out)
        self.assertIn("filename = ", self.out)

    def test_a_filter_with_no_knobs_emits_no_control_block(self):
        # A convolver has no Freq/Q/Gain; an empty control block is a parse
        # error, not a harmless no-op.
        self.assertNotIn("control = {", self.out)

    def test_a_filename_with_spaces_is_quoted(self):
        # AutoEQ names them "Sennheiser HD 650 minimum phase 48000Hz.wav".
        # Unquoted, SPA-JSON stops the value at the first space.
        self.assertIn('filename = "%s"' % IR, self.out)

    def test_a_stereo_impulse_response_gives_each_side_its_own_channel(self):
        # The one place the two channels genuinely differ: left takes channel
        # 0 of the wav and right takes channel 1.
        self.assertIn("channel = 0", node_line(self.out, "conv_l"))
        self.assertIn("channel = 1", node_line(self.out, "conv_r"))

    def test_numbers_stay_bare_while_strings_are_quoted(self):
        self.assertNotIn('channel = "0"', self.out)

    def test_a_shared_config_is_used_for_both_channels(self):
        mono = {"room": {"description": "d", "filters": [
            {"name": "conv", "label": "convolver", "config": {"filename": IR}}]}}
        out = render.render(device(mono))
        for ch in ("l", "r"):
            self.assertIn('filename = "%s"' % IR, node_line(out, "conv_%s" % ch))

    def test_it_is_still_a_one_stage_chain_with_a_valid_links_block(self):
        self.assertIn("# single-stage chain", self.out)
        self.assertEqual(self.out.count("{"), self.out.count("}"))

    def test_the_sink_is_named_after_the_profile_like_any_other(self):
        self.assertIn('node.name      = "eq_builtin_room"', self.out)
