#!/usr/bin/env python3
"""Render profiles into a PipeWire filter-chain config, one set per device.

Every profile becomes its own sink and they all load at once, so switching
between them is instant and can happen mid-playback -- essential for A/B
listening, where a restart destroys your sound memory of the previous setting.

Sinks are named eq_<devicetag>_<profile>, so several outputs can each carry
their own correction without colliding. Nothing matches those names literally:
`omarchy-eq ab status` reports the active profile instead, which keeps the
menu's checkmarks working whatever device you are on.

The playback side is pinned with target.object + node.dont-reconnect: without
that, WirePlumber re-routes each chain to whatever the current default sink is,
which chains the EQs into each other.

Two output shapes, same chains:

  standalone  a complete config for `pipewire -c`, run as a small client of the
              real daemon. Reloading it restarts one short-lived process and
              leaves every stream playing. This is what `apply` installs, and
              it is what makes auto-switching bearable -- a headphone connect
              must not take the audio server down with it.
  fragment    the old drop-in for pipewire.conf.d. Correct, but every change
              costs a full daemon restart. Kept for systems without systemd.
"""
import json
import sys

# `pipewire -c` starts a bare context: it needs to be told how to find spa
# factories and which modules to load before a filter chain can exist. This is
# the preamble from the shipped filter-chain.conf, trimmed to what we use.
STANDALONE_HEAD = """# Generated by omarchy-eq -- do not edit by hand.
# Loaded by:  pipewire -c ~/.config/omarchy-eq/chains.conf
# Regenerate with: omarchy-eq generate && omarchy-eq apply
context.properties = {
    log.level = 0
}
context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}
context.modules = [
    { name = libpipewire-module-rt flags = [ ifexists nofail ] }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }"""

FRAGMENT_HEAD = """# Generated by omarchy-eq -- do not edit by hand.
# Regenerate with: omarchy-eq generate && omarchy-eq apply
context.modules = ["""


def _block(name, items):
    body = " ".join("%s = %s" % (k, _value(v)) for k, v in items.items())
    return "%s = { %s }" % (name, body)


def _value(v):
    """Quote what SPA-JSON needs quoted and leave numbers bare.

    A convolver filename is a path -- unquoted it stops at the first space, and
    AutoEQ names them things like "Sennheiser HD 650 minimum phase 48000Hz.wav".
    """
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v) if isinstance(v, float) else str(v)
    return '"%s"' % str(v).replace('\\', '\\\\').replace('"', '\\"')


def node(f, ch):
    """One filter node, per channel.

    `config` is instantiation-time data (a convolver's impulse-response file);
    `control` is the runtime knobs (Freq/Q/Gain). A filter may carry a
    per-channel config -- a stereo impulse response takes channel 0 on the left
    and 1 on the right, which is the one place the two sides genuinely differ.
    """
    parts = ["type = builtin", "name = %s_%s" % (f["name"], ch),
             "label = %s" % f["label"]]
    conf = f.get("config_%s" % ch, f.get("config"))
    if conf:
        parts.append(_block("config", conf))
    if f.get("control"):
        parts.append(_block("control", f["control"]))
    return "          { %s }" % " ".join(parts)


def sink_name(tag, key):
    return "eq_%s_%s" % (tag, key)


def chain_block(tag, target, label, key, profile):
    chain = profile["filters"]
    nodes, links = [], []
    for ch in ("l", "r"):
        nodes += [node(f, ch) for f in chain]
        links += ['          { output = "%s_%s:Out" input = "%s_%s:In" }'
                  % (a["name"], ch, b["name"], ch)
                  for a, b in zip(chain, chain[1:])]
    first, last = chain[0]["name"], chain[-1]["name"]
    name = sink_name(tag, key)
    desc = "%s: %s" % (label, key.capitalize())
    return '''  { name = libpipewire-module-filter-chain
    args = {
      node.description = "%s"
      media.name       = "%s"
      filter.graph = {
        nodes = [
%s
        ]
        links = [
%s
        ]
        inputs  = [ "%s_l:In" "%s_r:In" ]
        outputs = [ "%s_l:Out" "%s_r:Out" ]
      }
      capture.props = {
        node.name      = "%s"
        media.class    = Audio/Sink
        audio.channels = 2
        audio.position = [ FL FR ]
      }
      playback.props = {
        node.name           = "%s_out"
        target.object       = "%s"
        node.dont-reconnect = true
        node.passive        = true
        audio.channels      = 2
        audio.position      = [ FL FR ]
      }
    }
  }''' % (desc, desc, "\n".join(nodes),
          "\n".join(links) or "          # single-stage chain",
          first, first, last, last, name, name, target)


def render(devices, standalone=True):
    """devices: [{tag, target, label, profiles}] -> config text."""
    out = [STANDALONE_HEAD if standalone else FRAGMENT_HEAD]
    for dev in devices:
        out.append("  # ---- %s (%s)" % (dev.get("label", dev["tag"]), dev["target"]))
        for key, p in dev["profiles"].items():
            out.append(chain_block(dev["tag"], dev["target"],
                                   dev.get("label", "Speakers"), key, p))
    out.append("]")
    return "\n".join(out)


def main():
    """argv: [--fragment] tag target label profiles.json [tag target ...]"""
    args, devices = sys.argv[1:], []
    standalone = True
    if args and args[0] == "--fragment":
        standalone, args = False, args[1:]
    if len(args) % 4:
        raise SystemExit("usage: render.py <tag> <target> <label> <profiles.json> ...")
    for i in range(0, len(args), 4):
        tag, target, label, path = args[i:i + 4]
        with open(path) as fh:
            profiles = json.load(fh).get("profiles", {})
        if profiles:
            devices.append({"tag": tag, "target": target, "label": label,
                            "profiles": profiles})
    if not devices:
        raise SystemExit("no profiles to render")
    sys.stdout.write(render(devices, standalone) + "\n")


if __name__ == "__main__":
    main()
