#!/usr/bin/env python3
"""Render profiles into a PipeWire filter-chain config, one set per device.

Every profile becomes its own sink and they all load at once, so switching
between them is instant and can happen mid-playback -- essential for A/B
listening, where a restart destroys your sound memory of the previous setting.

Sinks are named eq_<devicetag>_<profile>, so several outputs can each carry
their own correction without colliding. Nothing matches those names literally:
`omarchy-eq ab status` reports the active profile instead, which keeps the
menu's checkmarks working whatever device you are on.

The playback side is pinned with target.object + node.dont-reconnect: without
that, WirePlumber re-routes each chain to whatever the current default sink is,
which chains the EQs into each other.
"""
import json
import sys


def node(f, ch):
    ctrl = " ".join("%s = %s" % (k, v) for k, v in f["control"].items())
    return ('          { type = builtin name = %s_%s label = %s '
            'control = { %s } }' % (f["name"], ch, f["label"], ctrl))


def sink_name(tag, key):
    return "eq_%s_%s" % (tag, key)


def chain_block(tag, target, label, key, profile):
    chain = profile["filters"]
    nodes, links = [], []
    for ch in ("l", "r"):
        nodes += [node(f, ch) for f in chain]
        links += ['          { output = "%s_%s:Out" input = "%s_%s:In" }'
                  % (a["name"], ch, b["name"], ch)
                  for a, b in zip(chain, chain[1:])]
    first, last = chain[0]["name"], chain[-1]["name"]
    name = sink_name(tag, key)
    desc = "%s: %s" % (label, key.capitalize())
    return '''  { name = libpipewire-module-filter-chain
    args = {
      node.description = "%s"
      media.name       = "%s"
      filter.graph = {
        nodes = [
%s
        ]
        links = [
%s
        ]
        inputs  = [ "%s_l:In" "%s_r:In" ]
        outputs = [ "%s_l:Out" "%s_r:Out" ]
      }
      capture.props = {
        node.name      = "%s"
        media.class    = Audio/Sink
        audio.channels = 2
        audio.position = [ FL FR ]
      }
      playback.props = {
        node.name           = "%s_out"
        target.object       = "%s"
        node.dont-reconnect = true
        node.passive        = true
        audio.channels      = 2
        audio.position      = [ FL FR ]
      }
    }
  }''' % (desc, desc, "\n".join(nodes),
          "\n".join(links) or "          # single-stage chain",
          first, first, last, last, name, name, target)


def render(devices):
    """devices: [{tag, target, label, profiles}] -> config text."""
    out = ["# Generated by omarchy-eq -- do not edit by hand.",
           "# Regenerate with: omarchy-eq generate && omarchy-eq apply",
           "context.modules = ["]
    for dev in devices:
        out.append("  # ---- %s (%s)" % (dev.get("label", dev["tag"]), dev["target"]))
        for key, p in dev["profiles"].items():
            out.append(chain_block(dev["tag"], dev["target"],
                                   dev.get("label", "Speakers"), key, p))
    out.append("]")
    return "\n".join(out)


def main():
    """argv: tag target label profiles.json [tag target label profiles.json ...]"""
    args, devices = sys.argv[1:], []
    if len(args) % 4:
        raise SystemExit("usage: render.py <tag> <target> <label> <profiles.json> ...")
    for i in range(0, len(args), 4):
        tag, target, label, path = args[i:i + 4]
        with open(path) as fh:
            profiles = json.load(fh).get("profiles", {})
        if profiles:
            devices.append({"tag": tag, "target": target, "label": label,
                            "profiles": profiles})
    if not devices:
        raise SystemExit("no profiles to render")
    sys.stdout.write(render(devices) + "\n")


if __name__ == "__main__":
    main()
