#!/usr/bin/env python3
"""Render profiles.json into a PipeWire filter-chain config.

Every profile becomes its own sink and they all load at once, so switching
between them is instant and can happen mid-playback -- essential for A/B
listening, where a restart destroys your sound memory of the previous setting.

The playback side is pinned with target.object + node.dont-reconnect: without
that, WirePlumber re-routes each chain to whatever the current default sink is,
which chains the EQs into each other.
"""
import json
import sys


def node(prefix, f, ch):
    ctrl = " ".join("%s = %s" % (k, v) for k, v in f["control"].items())
    return ('          { type = builtin name = %s_%s label = %s '
            'control = { %s } }' % (f["name"], ch, f["label"], ctrl))


def render(profiles, target, prefix="eq"):
    out = ["# Generated by omarchy-eq -- do not edit by hand.",
           "# Regenerate with: omarchy-eq generate && omarchy-eq apply",
           "context.modules = ["]
    for key, p in profiles.items():
        chain = p["filters"]
        nodes, links = [], []
        for ch in ("l", "r"):
            nodes += [node(prefix, f, ch) for f in chain]
            links += ['          { output = "%s_%s:Out" input = "%s_%s:In" }'
                      % (a["name"], ch, b["name"], ch)
                      for a, b in zip(chain, chain[1:])]
        first, last = chain[0]["name"], chain[-1]["name"]
        out.append('''  { name = libpipewire-module-filter-chain
    args = {
      node.description = "Speakers: %s"
      media.name       = "Speakers: %s"
      filter.graph = {
        nodes = [
%s
        ]
        links = [
%s
        ]
        inputs  = [ "%s_l:In" "%s_r:In" ]
        outputs = [ "%s_l:Out" "%s_r:Out" ]
      }
      capture.props = {
        node.name      = "%s_%s"
        media.class    = Audio/Sink
        audio.channels = 2
        audio.position = [ FL FR ]
      }
      playback.props = {
        node.name           = "%s_%s_out"
        target.object       = "%s"
        node.dont-reconnect = true
        node.passive        = true
        audio.channels      = 2
        audio.position      = [ FL FR ]
      }
    }
  }''' % (key.capitalize(), key.capitalize(), "\n".join(nodes),
          "\n".join(links) or "          # single-stage chain",
          first, first, last, last, prefix, key, prefix, key, target))
    out.append("]")
    return "\n".join(out)


def main():
    data = json.load(open(sys.argv[1]))
    sys.stdout.write(render(data["profiles"], sys.argv[2]) + "\n")


if __name__ == "__main__":
    main()
